<?php

/**
 * This file was automatically generated by the Awesome Conflex API Model Generator Module
 * based in MYSQL/Mariadb database tables. After the generation you can modify
 * this model to fill with the best methods you think it should have.
 * 
 * 
 * Take care of this template and abuse of this.
 * 
 * Thank you for using it. github.com/mury12
 * 
 */

namespace MMWS\Controller;

use MMWS\Model\Diet;
use MMWS\Entity\DietEntity;
use MMWS\Factory\DietFactory;
use MMWS\Interfaces\AbstractController;
use MMWS\Response\DietWithStats;

class DietController extends AbstractController
{
    public $entity;
    public $model;

    public function __construct(array $data = [])
    {
        $model = new Diet();
        foreach ($data as $key => $prop) {
            if (property_exists($model, $key)) {
                $model->{$key} = $prop;
            }
        }
        $model->calcCalories();
        $this->entity = new DietEntity($model);
        $this->model = &$this->entity->model;
    }

    function withStats(Diet $diet)
    {
        $ctl = new MealController();
        $meals = $ctl->get();
        $withStats = DietFactory::withStatsByObject($diet, $ctl->withFoodStats($meals));
        return $withStats;
    }
}
