-- MySQL Script generated by MySQL Workbench
-- Fri Oct 20 18:47:14 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema dietacerta
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema dietacerta
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `dietacerta` DEFAULT CHARACTER SET utf8 ;
USE `dietacerta` ;

-- -----------------------------------------------------
-- Table `dietacerta`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dietacerta`.`user` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  `password` VARCHAR(100) NOT NULL,
  `act` TINYINT NOT NULL DEFAULT 1,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dietacerta`.`diet`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dietacerta`.`diet` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT NOT NULL,
  `weight` DOUBLE(10,2) NOT NULL,
  `carb` DOUBLE(10,2) NOT NULL,
  `prot` DOUBLE(10,2) NOT NULL,
  `tfat` DOUBLE(10,2) NOT NULL,
  `calories` DOUBLE(10,2) NOT NULL,
  `act` TINYINT NOT NULL DEFAULT 1,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  INDEX `fk_diet_user_idx` (`user_id` ASC),
  CONSTRAINT `fk_diet_user`
    FOREIGN KEY (`user_id`)
    REFERENCES `dietacerta`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dietacerta`.`food`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dietacerta`.`food` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NOT NULL,
  `weight` DOUBLE(10,2) NOT NULL,
  `user_id` INT NOT NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `carb` DOUBLE(10,2) NOT NULL,
  `prot` DOUBLE(10,2) NOT NULL,
  `tfat` DOUBLE(10,2) NOT NULL,
  `fiber` DOUBLE(10,2) NOT NULL,
  `sodium` DOUBLE(10,2) NOT NULL,
  `calories` DOUBLE(10,2) NOT NULL,
  `unit` VARCHAR(20) NOT NULL DEFAULT 'g',
  `act` TINYINT NOT NULL DEFAULT 1,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dietacerta`.`meal`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dietacerta`.`meal` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `diet_id` INT NOT NULL,
  `food_id` INT NOT NULL,
  `qtd` DOUBLE(10,2) NOT NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `act` TINYINT NOT NULL DEFAULT 1,
  PRIMARY KEY (`id`),
  INDEX `fk_meal_diet_id_idx` (`diet_id` ASC),
  INDEX `fk_meal_food_id_idx` (`food_id` ASC),
  CONSTRAINT `fk_meal_diet_id`
    FOREIGN KEY (`diet_id`)
    REFERENCES `dietacerta`.`diet` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_meal_food_id`
    FOREIGN KEY (`food_id`)
    REFERENCES `dietacerta`.`food` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
