<?php
/**
 * This file was automatically generated by the Awesome Conflex Webservice Model Generator Module
 * based in MYSQL/Mariadb database tables. After the generation you can modify
 * this model to fill with the best methods you think it should have.
 * 
 * 
 * Take care of this template and abuse of this.
 * 
 * Thank you for using it. github.com/mury12
 * 
 */
 
namespace MMWS\Model;
use MMWS\Entity\DcDietTemplatesEntity;

class DcDietTemplates
{

    /**
     * @var String $table the table name for this model;
     */   
    public $table = 'dc_diet_templates';


    /**
     * @var MMWS\Entity\DcDietTemplatesEntity $entity the entity for this model
     */
    public $entity;

    public $id;
    public $baseKcalKilo;
    public $baseProteinKilo;
    public $baseFatKilo;
    public $baseCarbKilo;
    public $createdAt;
    public $status;
    public $createdBy;
    public $roleid;
    public $name;
    

    public function __construct($id = null, $baseKcalKilo = null, $baseProteinKilo = null, $baseFatKilo = null, $baseCarbKilo = null, $createdAt = null, $status = null, $createdBy = null, $roleid = null, $name = null)
    {
        $this->id = $id;
	    $this->baseKcalKilo = $baseKcalKilo;
	    $this->baseProteinKilo = $baseProteinKilo;
	    $this->baseFatKilo = $baseFatKilo;
	    $this->baseCarbKilo = $baseCarbKilo;
	    $this->createdAt = $createdAt;
	    $this->status = $status;
	    $this->createdBy = $createdBy;
	    $this->roleid = $roleid;
	    $this->name = $name;
	    
        $this->entity = new DcDietTemplatesEntity($this);
    }

    /**
     * Saves this instance to the database
     */
    public function save()
    {
        return $this->entity->save();
    }

    /**
     * Updates this instance to the database
     */
    public function update()
    {
        return $this->entity->update();
    }

    /**
     * Get one instance from the database
     */
    public function get()
    {
        return $this->entity->get();
    }

    /**
     * Get all the instances from the database and returns 
     * as an SELF::CLASS array
     */
    public function getAll()
    {
        return $this->entity->getAll();
    }

    /**
     * Removes this instance from the database
     */
    public function delete()
    {
        return $this->entity->delete();
    }
}