<?php
/**
 * This file was automatically generated by the Awesome Conflex Webservice Model Generator Module
 * based in MYSQL/Mariadb database tables. After the generation you can modify
 * this model to fill with the best methods you think it should have.
 * 
 * 
 * Take care of this template and abuse of this.
 * 
 * Thank you for using it. github.com/mury12
 * 
 */
 
namespace MMWS\Model;
use MMWS\Entity\DcLogActionsEntity;

class DcLogActions
{

    /**
     * @var String $table the table name for this model;
     */   
    public $table = 'dc_log_actions';


    /**
     * @var MMWS\Entity\DcLogActionsEntity $entity the entity for this model
     */
    public $entity;

    public $id;
    public $actionName;
    public $actionRoute;
    public $actionDescription;
    public $status;
    

    public function __construct($id = null, $actionName = null, $actionRoute = null, $actionDescription = null, $status = null)
    {
        $this->id = $id;
	    $this->actionName = $actionName;
	    $this->actionRoute = $actionRoute;
	    $this->actionDescription = $actionDescription;
	    $this->status = $status;
	    
        $this->entity = new DcLogActionsEntity($this);
    }

    /**
     * Saves this instance to the database
     */
    public function save()
    {
        return $this->entity->save();
    }

    /**
     * Updates this instance to the database
     */
    public function update()
    {
        return $this->entity->update();
    }

    /**
     * Get one instance from the database
     */
    public function get()
    {
        return $this->entity->get();
    }

    /**
     * Get all the instances from the database and returns 
     * as an SELF::CLASS array
     */
    public function getAll()
    {
        return $this->entity->getAll();
    }

    /**
     * Removes this instance from the database
     */
    public function delete()
    {
        return $this->entity->delete();
    }
}