<?php

/**
 * This file was automatically generated by the Awesome Conflex API Model Generator Module
 * based in MYSQL/Mariadb database tables. After the generation you can modify
 * this model to fill with the best methods you think it should have.
 * 
 * 
 * Take care of this template and abuse of this.
 * 
 * Thank you for using it. github.com/mury12
 * 
 */

namespace MMWS\Controller;

use MMWS\Model\Meal;
use MMWS\Entity\MealEntity;
use MMWS\Abstracts\Controller;
use MMWS\Model\Food;
use MMWS\Model\MealStats;
use MMWS\Model\Stats;
use MMWS\Response\MealWithStats;

class MealController extends Controller
{
    public $entity;
    public $model;

    public function __construct(array $data = [])
    {
        $model = new Meal();
        foreach ($data as $key => $prop) {
            if (property_exists($model, $key)) {
                $model->{$key} = $prop;
            }
        }
        $this->entity = new MealEntity($model);
        $this->model = &$this->entity->model;
    }

    /**
     * Bulk creates meals
     * @param MMWS\Model\Meal[] $instances
     */
    public function bulkCreate(array $instances)
    {
        return $this->entity->bulkCreate($instances);
    }

    public function getAllFromToday(array $filters = [], bool $asobj = true, bool $and = true)
    {
        return $this->entity->getAllFromToday($filters, $asobj, $and);
    }

    public function withFoodStats($meals)
    {

        if (!is_array($meals))
            $meals = [$meals];

        $foodIds = array_map(function ($meal) {
            return $meal->foodId;
        }, $meals);

        if (!sizeof($foodIds)) return $meals;

        $foodCtl = new FoodController();
        $queryStr = implode(',', $foodIds);
        $foods = $foodCtl->get(['filters' => [
            'id_in' => $queryStr
        ]], true);

        /**
         * @param Meal $meal
         */
        return array_map(function ($meal) use ($foods) {

            $food = array_filter(
                $foods,
                function ($food) use ($meal) {
                    return $food->id === $meal->foodId;
                }
            );
            if (!$food) return $meal;
            $food = array_shift($food);

            if ($food instanceof Food) {
                $stats = new MealStats($food, $meal->qtd);

                $withStats = new MealWithStats();
                $withStats->id = $meal->id;
                $withStats->stats = $stats;
                $withStats->food = $food;

                return $withStats;
            }
            return $meal;
        }, $meals);
    }
}
